version: "3"
services:
  database:
    build:
      context:
        ./mongodb
    container_name: coderunner-mongo
    ports:
      - "27018:27017"


  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tests
    restart: always


  redis:
    image: "redis:latest"
    container_name: coderunner-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:management"
    container_name: coderunner-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=your_username
      - RABBITMQ_DEFAULT_PASS=your_password

  application:
    build: .
    container_name: coderunner-api
    ports:
      - "8090:8090"
    depends_on:
      - database
      - redis
      - rabbitmq
      - postgres
