version: "3.8"
services:
  database:
    build:
      context:
        ./mongodb
    container_name: coderunner-mongo
    restart: always
    ports:
      - "27018:27017"

  redis:
    image: "redis:latest"
    container_name: coderunner-redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:management"
    container_name: coderunner-rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=your_username
      - RABBITMQ_DEFAULT_PASS=your_password

  application:
    build: .
    container_name: coderunner-api
    restart: always
    ports:
      - "8090:8090"
    networks:
      - back_db_to_coderunner
      - default
    depends_on:
      - database
      - redis
      - rabbitmq


networks:
  back_db_to_coderunner:
    external: true


